// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nivik/mypa/internal/orchestrator (interfaces: TelegramClient,TwilioClient,AudioClient,LLMClient,CalendarClient,GmailClient,TasksClient,TavilyClient,DBClient)
//
// Generated by this command:
//
//	mockgen -destination internal/orchestrator/mocks/ports_mock.go -package mocks github.com/nivik/mypa/internal/orchestrator TelegramClient,TwilioClient,AudioClient,LLMClient,CalendarClient,GmailClient,TasksClient,TavilyClient,DBClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gmail "github.com/nivik/mypa/internal/gmail"
	llm "github.com/nivik/mypa/internal/llm"
	models "github.com/nivik/mypa/internal/models"
	pgvector "github.com/pgvector/pgvector-go"
	gomock "go.uber.org/mock/gomock"
	calendar "google.golang.org/api/calendar/v3"
	tasks "google.golang.org/api/tasks/v1"
)

// MockTelegramClient is a mock of TelegramClient interface.
type MockTelegramClient struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramClientMockRecorder
	isgomock struct{}
}

// MockTelegramClientMockRecorder is the mock recorder for MockTelegramClient.
type MockTelegramClientMockRecorder struct {
	mock *MockTelegramClient
}

// NewMockTelegramClient creates a new mock instance.
func NewMockTelegramClient(ctrl *gomock.Controller) *MockTelegramClient {
	mock := &MockTelegramClient{ctrl: ctrl}
	mock.recorder = &MockTelegramClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramClient) EXPECT() *MockTelegramClientMockRecorder {
	return m.recorder
}

// DownloadFile mocks base method.
func (m *MockTelegramClient) DownloadFile(ctx context.Context, filePath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, filePath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockTelegramClientMockRecorder) DownloadFile(ctx, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockTelegramClient)(nil).DownloadFile), ctx, filePath)
}

// GetFile mocks base method.
func (m *MockTelegramClient) GetFile(ctx context.Context, fileID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, fileID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockTelegramClientMockRecorder) GetFile(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockTelegramClient)(nil).GetFile), ctx, fileID)
}

// SendMessage mocks base method.
func (m *MockTelegramClient) SendMessage(ctx context.Context, chatID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, chatID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockTelegramClientMockRecorder) SendMessage(ctx, chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockTelegramClient)(nil).SendMessage), ctx, chatID, text)
}

// MockTwilioClient is a mock of TwilioClient interface.
type MockTwilioClient struct {
	ctrl     *gomock.Controller
	recorder *MockTwilioClientMockRecorder
	isgomock struct{}
}

// MockTwilioClientMockRecorder is the mock recorder for MockTwilioClient.
type MockTwilioClientMockRecorder struct {
	mock *MockTwilioClient
}

// NewMockTwilioClient creates a new mock instance.
func NewMockTwilioClient(ctrl *gomock.Controller) *MockTwilioClient {
	mock := &MockTwilioClient{ctrl: ctrl}
	mock.recorder = &MockTwilioClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTwilioClient) EXPECT() *MockTwilioClientMockRecorder {
	return m.recorder
}

// DownloadMedia mocks base method.
func (m *MockTwilioClient) DownloadMedia(ctx context.Context, mediaURL string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadMedia", ctx, mediaURL)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadMedia indicates an expected call of DownloadMedia.
func (mr *MockTwilioClientMockRecorder) DownloadMedia(ctx, mediaURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadMedia", reflect.TypeOf((*MockTwilioClient)(nil).DownloadMedia), ctx, mediaURL)
}

// SendMessage mocks base method.
func (m *MockTwilioClient) SendMessage(ctx context.Context, to, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, to, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockTwilioClientMockRecorder) SendMessage(ctx, to, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockTwilioClient)(nil).SendMessage), ctx, to, body)
}

// MockAudioClient is a mock of AudioClient interface.
type MockAudioClient struct {
	ctrl     *gomock.Controller
	recorder *MockAudioClientMockRecorder
	isgomock struct{}
}

// MockAudioClientMockRecorder is the mock recorder for MockAudioClient.
type MockAudioClientMockRecorder struct {
	mock *MockAudioClient
}

// NewMockAudioClient creates a new mock instance.
func NewMockAudioClient(ctrl *gomock.Controller) *MockAudioClient {
	mock := &MockAudioClient{ctrl: ctrl}
	mock.recorder = &MockAudioClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudioClient) EXPECT() *MockAudioClientMockRecorder {
	return m.recorder
}

// TranscribeAudio mocks base method.
func (m *MockAudioClient) TranscribeAudio(ctx context.Context, audioData []byte, filename string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscribeAudio", ctx, audioData, filename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranscribeAudio indicates an expected call of TranscribeAudio.
func (mr *MockAudioClientMockRecorder) TranscribeAudio(ctx, audioData, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscribeAudio", reflect.TypeOf((*MockAudioClient)(nil).TranscribeAudio), ctx, audioData, filename)
}

// MockLLMClient is a mock of LLMClient interface.
type MockLLMClient struct {
	ctrl     *gomock.Controller
	recorder *MockLLMClientMockRecorder
	isgomock struct{}
}

// MockLLMClientMockRecorder is the mock recorder for MockLLMClient.
type MockLLMClientMockRecorder struct {
	mock *MockLLMClient
}

// NewMockLLMClient creates a new mock instance.
func NewMockLLMClient(ctrl *gomock.Controller) *MockLLMClient {
	mock := &MockLLMClient{ctrl: ctrl}
	mock.recorder = &MockLLMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMClient) EXPECT() *MockLLMClientMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockLLMClient) Chat(ctx context.Context, systemPrompt string, history []models.ChatMessage, userMessage string) (*llm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", ctx, systemPrompt, history, userMessage)
	ret0, _ := ret[0].(*llm.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockLLMClientMockRecorder) Chat(ctx, systemPrompt, history, userMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockLLMClient)(nil).Chat), ctx, systemPrompt, history, userMessage)
}

// GenerateEmbedding mocks base method.
func (m *MockLLMClient) GenerateEmbedding(ctx context.Context, text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateEmbedding", ctx, text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateEmbedding indicates an expected call of GenerateEmbedding.
func (mr *MockLLMClientMockRecorder) GenerateEmbedding(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateEmbedding", reflect.TypeOf((*MockLLMClient)(nil).GenerateEmbedding), ctx, text)
}

// MockCalendarClient is a mock of CalendarClient interface.
type MockCalendarClient struct {
	ctrl     *gomock.Controller
	recorder *MockCalendarClientMockRecorder
	isgomock struct{}
}

// MockCalendarClientMockRecorder is the mock recorder for MockCalendarClient.
type MockCalendarClientMockRecorder struct {
	mock *MockCalendarClient
}

// NewMockCalendarClient creates a new mock instance.
func NewMockCalendarClient(ctrl *gomock.Controller) *MockCalendarClient {
	mock := &MockCalendarClient{ctrl: ctrl}
	mock.recorder = &MockCalendarClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalendarClient) EXPECT() *MockCalendarClientMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockCalendarClient) CreateEvent(ctx context.Context, ev models.CalendarEvent) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, ev)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockCalendarClientMockRecorder) CreateEvent(ctx, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockCalendarClient)(nil).CreateEvent), ctx, ev)
}

// DeleteEvent mocks base method.
func (m *MockCalendarClient) DeleteEvent(ctx context.Context, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockCalendarClientMockRecorder) DeleteEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockCalendarClient)(nil).DeleteEvent), ctx, eventID)
}

// ListEvents mocks base method.
func (m *MockCalendarClient) ListEvents(ctx context.Context, timeMin, timeMax, q string) ([]*calendar.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, timeMin, timeMax, q)
	ret0, _ := ret[0].([]*calendar.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockCalendarClientMockRecorder) ListEvents(ctx, timeMin, timeMax, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockCalendarClient)(nil).ListEvents), ctx, timeMin, timeMax, q)
}

// UpdateEvent mocks base method.
func (m *MockCalendarClient) UpdateEvent(ctx context.Context, eventID string, ev models.CalendarEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", ctx, eventID, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockCalendarClientMockRecorder) UpdateEvent(ctx, eventID, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockCalendarClient)(nil).UpdateEvent), ctx, eventID, ev)
}

// MockGmailClient is a mock of GmailClient interface.
type MockGmailClient struct {
	ctrl     *gomock.Controller
	recorder *MockGmailClientMockRecorder
	isgomock struct{}
}

// MockGmailClientMockRecorder is the mock recorder for MockGmailClient.
type MockGmailClientMockRecorder struct {
	mock *MockGmailClient
}

// NewMockGmailClient creates a new mock instance.
func NewMockGmailClient(ctrl *gomock.Controller) *MockGmailClient {
	mock := &MockGmailClient{ctrl: ctrl}
	mock.recorder = &MockGmailClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGmailClient) EXPECT() *MockGmailClientMockRecorder {
	return m.recorder
}

// ApplyLabel mocks base method.
func (m *MockGmailClient) ApplyLabel(ctx context.Context, userID, messageID, labelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyLabel", ctx, userID, messageID, labelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyLabel indicates an expected call of ApplyLabel.
func (mr *MockGmailClientMockRecorder) ApplyLabel(ctx, userID, messageID, labelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyLabel", reflect.TypeOf((*MockGmailClient)(nil).ApplyLabel), ctx, userID, messageID, labelID)
}

// ArchiveEmail mocks base method.
func (m *MockGmailClient) ArchiveEmail(ctx context.Context, userID, messageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveEmail", ctx, userID, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveEmail indicates an expected call of ArchiveEmail.
func (mr *MockGmailClientMockRecorder) ArchiveEmail(ctx, userID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveEmail", reflect.TypeOf((*MockGmailClient)(nil).ArchiveEmail), ctx, userID, messageID)
}

// DraftReply mocks base method.
func (m *MockGmailClient) DraftReply(ctx context.Context, userID, messageID, replyText string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DraftReply", ctx, userID, messageID, replyText)
	ret0, _ := ret[0].(error)
	return ret0
}

// DraftReply indicates an expected call of DraftReply.
func (mr *MockGmailClientMockRecorder) DraftReply(ctx, userID, messageID, replyText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DraftReply", reflect.TypeOf((*MockGmailClient)(nil).DraftReply), ctx, userID, messageID, replyText)
}

// ListLabels mocks base method.
func (m *MockGmailClient) ListLabels(ctx context.Context, userID string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLabels", ctx, userID)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLabels indicates an expected call of ListLabels.
func (mr *MockGmailClientMockRecorder) ListLabels(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLabels", reflect.TypeOf((*MockGmailClient)(nil).ListLabels), ctx, userID)
}

// ReadEmail mocks base method.
func (m *MockGmailClient) ReadEmail(ctx context.Context, userID, messageID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEmail", ctx, userID, messageID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadEmail indicates an expected call of ReadEmail.
func (mr *MockGmailClientMockRecorder) ReadEmail(ctx, userID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEmail", reflect.TypeOf((*MockGmailClient)(nil).ReadEmail), ctx, userID, messageID)
}

// SearchEmails mocks base method.
func (m *MockGmailClient) SearchEmails(ctx context.Context, userID, query string, maxResults int64) ([]gmail.EmailSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchEmails", ctx, userID, query, maxResults)
	ret0, _ := ret[0].([]gmail.EmailSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchEmails indicates an expected call of SearchEmails.
func (mr *MockGmailClientMockRecorder) SearchEmails(ctx, userID, query, maxResults any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchEmails", reflect.TypeOf((*MockGmailClient)(nil).SearchEmails), ctx, userID, query, maxResults)
}

// SoftDeleteEmail mocks base method.
func (m *MockGmailClient) SoftDeleteEmail(ctx context.Context, userID, messageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteEmail", ctx, userID, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteEmail indicates an expected call of SoftDeleteEmail.
func (mr *MockGmailClientMockRecorder) SoftDeleteEmail(ctx, userID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteEmail", reflect.TypeOf((*MockGmailClient)(nil).SoftDeleteEmail), ctx, userID, messageID)
}

// CreateLabel mocks base method.
func (m *MockGmailClient) CreateLabel(ctx context.Context, userID, labelName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLabel", ctx, userID, labelName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLabel indicates an expected call of CreateLabel.
func (mr *MockGmailClientMockRecorder) CreateLabel(ctx, userID, labelName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLabel", reflect.TypeOf((*MockGmailClient)(nil).CreateLabel), ctx, userID, labelName)
}

// MockTasksClient is a mock of TasksClient interface.
type MockTasksClient struct {
	ctrl     *gomock.Controller
	recorder *MockTasksClientMockRecorder
	isgomock struct{}
}

// MockTasksClientMockRecorder is the mock recorder for MockTasksClient.
type MockTasksClientMockRecorder struct {
	mock *MockTasksClient
}

// NewMockTasksClient creates a new mock instance.
func NewMockTasksClient(ctrl *gomock.Controller) *MockTasksClient {
	mock := &MockTasksClient{ctrl: ctrl}
	mock.recorder = &MockTasksClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTasksClient) EXPECT() *MockTasksClientMockRecorder {
	return m.recorder
}

// CompleteTask mocks base method.
func (m *MockTasksClient) CompleteTask(ctx context.Context, userID, listID, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteTask", ctx, userID, listID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteTask indicates an expected call of CompleteTask.
func (mr *MockTasksClientMockRecorder) CompleteTask(ctx, userID, listID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteTask", reflect.TypeOf((*MockTasksClient)(nil).CompleteTask), ctx, userID, listID, taskID)
}

// CreateTask mocks base method.
func (m *MockTasksClient) CreateTask(ctx context.Context, userID, listID, title, notes, due string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, userID, listID, title, notes, due)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTasksClientMockRecorder) CreateTask(ctx, userID, listID, title, notes, due any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTasksClient)(nil).CreateTask), ctx, userID, listID, title, notes, due)
}

// CreateTaskList mocks base method.
func (m *MockTasksClient) CreateTaskList(ctx context.Context, userID, title string) (*tasks.TaskList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskList", ctx, userID, title)
	ret0, _ := ret[0].(*tasks.TaskList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTaskList indicates an expected call of CreateTaskList.
func (mr *MockTasksClientMockRecorder) CreateTaskList(ctx, userID, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskList", reflect.TypeOf((*MockTasksClient)(nil).CreateTaskList), ctx, userID, title)
}

// DeleteTask mocks base method.
func (m *MockTasksClient) DeleteTask(ctx context.Context, userID, listID, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, userID, listID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTasksClientMockRecorder) DeleteTask(ctx, userID, listID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTasksClient)(nil).DeleteTask), ctx, userID, listID, taskID)
}

// ListTaskLists mocks base method.
func (m *MockTasksClient) ListTaskLists(ctx context.Context, userID string) ([]*tasks.TaskList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskLists", ctx, userID)
	ret0, _ := ret[0].([]*tasks.TaskList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTaskLists indicates an expected call of ListTaskLists.
func (mr *MockTasksClientMockRecorder) ListTaskLists(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskLists", reflect.TypeOf((*MockTasksClient)(nil).ListTaskLists), ctx, userID)
}

// ListTasks mocks base method.
func (m *MockTasksClient) ListTasks(ctx context.Context, userID, listID string) ([]*tasks.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", ctx, userID, listID)
	ret0, _ := ret[0].([]*tasks.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockTasksClientMockRecorder) ListTasks(ctx, userID, listID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockTasksClient)(nil).ListTasks), ctx, userID, listID)
}

// MockTavilyClient is a mock of TavilyClient interface.
type MockTavilyClient struct {
	ctrl     *gomock.Controller
	recorder *MockTavilyClientMockRecorder
	isgomock struct{}
}

// MockTavilyClientMockRecorder is the mock recorder for MockTavilyClient.
type MockTavilyClientMockRecorder struct {
	mock *MockTavilyClient
}

// NewMockTavilyClient creates a new mock instance.
func NewMockTavilyClient(ctrl *gomock.Controller) *MockTavilyClient {
	mock := &MockTavilyClient{ctrl: ctrl}
	mock.recorder = &MockTavilyClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTavilyClient) EXPECT() *MockTavilyClientMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockTavilyClient) Search(ctx context.Context, query string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockTavilyClientMockRecorder) Search(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockTavilyClient)(nil).Search), ctx, query)
}

// MockDBClient is a mock of DBClient interface.
type MockDBClient struct {
	ctrl     *gomock.Controller
	recorder *MockDBClientMockRecorder
	isgomock struct{}
}

// MockDBClientMockRecorder is the mock recorder for MockDBClient.
type MockDBClientMockRecorder struct {
	mock *MockDBClient
}

// NewMockDBClient creates a new mock instance.
func NewMockDBClient(ctrl *gomock.Controller) *MockDBClient {
	mock := &MockDBClient{ctrl: ctrl}
	mock.recorder = &MockDBClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBClient) EXPECT() *MockDBClientMockRecorder {
	return m.recorder
}

// GetLastAuditLogForUser mocks base method.
func (m *MockDBClient) GetLastAuditLogForUser(userID string) (*models.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastAuditLogForUser", userID)
	ret0, _ := ret[0].(*models.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastAuditLogForUser indicates an expected call of GetLastAuditLogForUser.
func (mr *MockDBClientMockRecorder) GetLastAuditLogForUser(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastAuditLogForUser", reflect.TypeOf((*MockDBClient)(nil).GetLastAuditLogForUser), userID)
}

// GetUniqueUsers mocks base method.
func (m *MockDBClient) GetUniqueUsers() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUniqueUsers")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUniqueUsers indicates an expected call of GetUniqueUsers.
func (mr *MockDBClientMockRecorder) GetUniqueUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUniqueUsers", reflect.TypeOf((*MockDBClient)(nil).GetUniqueUsers))
}

// LogInteraction mocks base method.
func (m *MockDBClient) LogInteraction(log models.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogInteraction", log)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogInteraction indicates an expected call of LogInteraction.
func (mr *MockDBClientMockRecorder) LogInteraction(log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogInteraction", reflect.TypeOf((*MockDBClient)(nil).LogInteraction), log)
}

// SaveMemory mocks base method.
func (m *MockDBClient) SaveMemory(memory models.Memory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMemory", memory)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMemory indicates an expected call of SaveMemory.
func (mr *MockDBClientMockRecorder) SaveMemory(memory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMemory", reflect.TypeOf((*MockDBClient)(nil).SaveMemory), memory)
}

// SearchMemories mocks base method.
func (m *MockDBClient) SearchMemories(userID string, embedding pgvector.Vector, limit int) ([]models.Memory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMemories", userID, embedding, limit)
	ret0, _ := ret[0].([]models.Memory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMemories indicates an expected call of SearchMemories.
func (mr *MockDBClientMockRecorder) SearchMemories(userID, embedding, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMemories", reflect.TypeOf((*MockDBClient)(nil).SearchMemories), userID, embedding, limit)
}
