// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type PairingCode struct {
	ID          string    `json:"id"`
	Code        string    `json:"code"`
	Role        string    `json:"role"`
	FamilyGroup string    `json:"familyGroup"`
	ExpiresAt   time.Time `json:"expiresAt"`
	IsUsed      bool      `json:"isUsed"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Query struct {
}

type User struct {
	ID          string    `json:"id"`
	PlatformID  string    `json:"platformId"`
	Name        string    `json:"name"`
	Role        string    `json:"role"`
	FamilyGroup string    `json:"familyGroup"`
	CreatedAt   time.Time `json:"createdAt"`
}
